import { Challenge } from '../types';

export const CHALLENGES: Challenge[] = [
  {
    id: 'meditation_30',
    name: '30 Jours de Méditation',
    description: 'Médite chaque jour pendant 10 minutes. Développe ta concentration et ta paix intérieure.',
    icon: 'leaf',
    color: '#10B981',
    duration: 30,
    habitConfig: {
      name: 'Méditer 10 min',
      type: 'quantitative',
      target: 10,
      unit: 'min',
    },
    category: 'personal_development',
  },
  {
    id: 'no_sugar_30',
    name: '30 Jours Sans Sucre',
    description: 'Élimine le sucre ajouté de ton alimentation pendant 30 jours.',
    icon: 'close-circle',
    color: '#EF4444',
    duration: 30,
    habitConfig: {
      name: 'Pas de sucre',
      type: 'binary',
      target: null,
      unit: null,
    },
    category: 'health',
  },
  {
    id: 'reading_30',
    name: '30 Jours de Lecture',
    description: 'Lis au moins 20 minutes chaque jour. Élargis tes connaissances.',
    icon: 'book',
    color: '#3B82F6',
    duration: 30,
    habitConfig: {
      name: 'Lire 20 min',
      type: 'quantitative',
      target: 20,
      unit: 'min',
    },
    category: 'reading',
  },
  {
    id: 'sport_30',
    name: '30 Jours de Sport',
    description: 'Fais 30 minutes d\'exercice chaque jour. Transforme ton corps.',
    icon: 'fitness',
    color: '#F97316',
    duration: 30,
    habitConfig: {
      name: '30 min sport',
      type: 'quantitative',
      target: 30,
      unit: 'min',
    },
    category: 'sport',
  },
  {
    id: 'water_14',
    name: '14 Jours d\'Hydratation',
    description: 'Bois 2 litres d\'eau par jour pendant 2 semaines.',
    icon: 'water',
    color: '#06B6D4',
    duration: 14,
    habitConfig: {
      name: 'Boire 2L d\'eau',
      type: 'quantitative',
      target: 2000,
      unit: 'ml',
    },
    category: 'health',
  },
  {
    id: 'sleep_21',
    name: '21 Jours de Sommeil',
    description: 'Couche-toi avant 23h pendant 21 jours. Améliore ta qualité de vie.',
    icon: 'moon',
    color: '#8B5CF6',
    duration: 21,
    habitConfig: {
      name: 'Coucher avant 23h',
      type: 'binary',
      target: null,
      unit: null,
    },
    category: 'sleep',
  },
  {
    id: 'no_phone_7',
    name: '7 Jours Digital Detox',
    description: 'Pas de réseaux sociaux pendant une semaine complète.',
    icon: 'phone-portrait',
    color: '#64748B',
    duration: 7,
    habitConfig: {
      name: 'Pas de réseaux sociaux',
      type: 'binary',
      target: null,
      unit: null,
    },
    category: 'productivity',
  },
  {
    id: 'journal_30',
    name: '30 Jours de Journaling',
    description: 'Écris dans ton journal chaque jour. Clarifie tes pensées.',
    icon: 'journal',
    color: '#F59E0B',
    duration: 30,
    habitConfig: {
      name: 'Journaling',
      type: 'binary',
      target: null,
      unit: null,
    },
    category: 'personal_development',
  },
];
