import { PresetHabit } from '../types';

export const PRESET_HABITS: PresetHabit[] = [
  // Health
  {
    name: 'Boire 2L d\'eau',
    type: 'quantitative',
    target: 2000,
    unit: 'ml',
    icon: 'water',
    color: '#3B82F6',
    category: 'health',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Manger sainement',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'nutrition',
    color: '#10B981',
    category: 'health',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Pas de sucre',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'close-circle',
    color: '#EF4444',
    category: 'health',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },

  // Sport
  {
    name: '30 min sport',
    type: 'quantitative',
    target: 30,
    unit: 'min',
    icon: 'fitness',
    color: '#F97316',
    category: 'sport',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: '10 000 pas',
    type: 'quantitative',
    target: 10000,
    unit: 'pas',
    icon: 'walk',
    color: '#14B8A6',
    category: 'sport',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Étirements',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'body',
    color: '#EC4899',
    category: 'sport',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },

  // Productivity
  {
    name: 'Deep work 2h',
    type: 'quantitative',
    target: 120,
    unit: 'min',
    icon: 'laptop',
    color: '#7C3AED',
    category: 'productivity',
    frequency: { type: 'custom', days: [1, 2, 3, 4, 5] },
  },
  {
    name: 'Pas de réseaux sociaux',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'phone-portrait',
    color: '#EF4444',
    category: 'productivity',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'To-do list du jour',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'checkbox',
    color: '#3B82F6',
    category: 'productivity',
    frequency: { type: 'custom', days: [1, 2, 3, 4, 5] },
  },

  // Personal Development
  {
    name: 'Méditer 10 min',
    type: 'quantitative',
    target: 10,
    unit: 'min',
    icon: 'leaf',
    color: '#10B981',
    category: 'personal_development',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Journaling',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'journal',
    color: '#F59E0B',
    category: 'personal_development',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Gratitude',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'heart',
    color: '#EC4899',
    category: 'personal_development',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },

  // Sleep
  {
    name: 'Coucher avant 23h',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'moon',
    color: '#6366F1',
    category: 'sleep',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: '8h de sommeil',
    type: 'quantitative',
    target: 8,
    unit: 'h',
    icon: 'bed',
    color: '#8B5CF6',
    category: 'sleep',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Pas d\'écran 1h avant',
    type: 'binary',
    target: null,
    unit: null,
    icon: 'eye-off',
    color: '#64748B',
    category: 'sleep',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },

  // Reading
  {
    name: 'Lire 20 min',
    type: 'quantitative',
    target: 20,
    unit: 'min',
    icon: 'book',
    color: '#F59E0B',
    category: 'reading',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
  {
    name: 'Lire 10 pages',
    type: 'quantitative',
    target: 10,
    unit: 'pages',
    icon: 'book-outline',
    color: '#06B6D4',
    category: 'reading',
    frequency: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
  },
];

export const CATEGORIES: { key: string; label: string; icon: string; color: string }[] = [
  { key: 'health', label: 'Santé', icon: 'heart', color: '#10B981' },
  { key: 'sport', label: 'Sport', icon: 'fitness', color: '#F97316' },
  { key: 'productivity', label: 'Productivité', icon: 'rocket', color: '#7C3AED' },
  { key: 'personal_development', label: 'Développement personnel', icon: 'sparkles', color: '#F59E0B' },
  { key: 'sleep', label: 'Sommeil', icon: 'moon', color: '#6366F1' },
  { key: 'reading', label: 'Lecture', icon: 'book', color: '#3B82F6' },
];

export const HABIT_ICONS = [
  'water', 'nutrition', 'fitness', 'walk', 'body', 'laptop',
  'phone-portrait', 'checkbox', 'leaf', 'journal', 'heart',
  'moon', 'bed', 'eye-off', 'book', 'book-outline', 'rocket',
  'sparkles', 'close-circle', 'star', 'trophy', 'flame',
  'time', 'musical-notes', 'camera', 'brush', 'code-slash',
  'globe', 'people', 'cafe', 'restaurant', 'bicycle',
];
